-- Early Warning & Repair Decision Workflow (TruckFixr V1.0).
--
-- Adds:
--   1. Issue-record fields on "defects" so a defect can carry its source
--      (inspection / diagnostic / manual report / fault code), structured
--      symptoms + fault codes, a safety flag, a normalized recommended action,
--      an optional linked trailer, and a closed timestamp.
--   2. A new "earlyWarningFlags" table that stores deterministic, rule-based
--      early-warning signals generated by the backend.
--
-- This migration is written for Postgres / Supabase and is intentionally
-- idempotent (IF NOT EXISTS everywhere). It is non-destructive: every new
-- column is nullable or defaulted, and no existing column is dropped or
-- retyped. Apply it with the rest of the Drizzle migrations or via
-- scripts/verify/apply-readiness-migrations.ts.

-- 1. Issue-record fields on defects -----------------------------------------
ALTER TABLE "defects"
ADD COLUMN IF NOT EXISTS "sourceType" varchar(32) NOT NULL DEFAULT 'manual_report',
ADD COLUMN IF NOT EXISTS "sourceRecordId" varchar(128),
ADD COLUMN IF NOT EXISTS "trailerId" varchar(64),
ADD COLUMN IF NOT EXISTS "symptoms" jsonb,
ADD COLUMN IF NOT EXISTS "faultCodes" jsonb,
ADD COLUMN IF NOT EXISTS "safetyRelated" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "recommendedAction" varchar(32),
ADD COLUMN IF NOT EXISTS "closedAt" timestamp;

-- Backfill sourceType for existing rows: defects created from an inspection
-- already carry an inspectionId; everything else stays as the manual default.
UPDATE "defects"
SET "sourceType" = 'inspection'
WHERE "inspectionId" IS NOT NULL
  AND "sourceType" = 'manual_report';

CREATE INDEX IF NOT EXISTS "defects_fleet_status_idx"
  ON "defects" ("fleetId", "status");
CREATE INDEX IF NOT EXISTS "defects_vehicle_created_idx"
  ON "defects" ("vehicleId", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS "defects_source_idx"
  ON "defects" ("sourceType", "sourceRecordId");

-- 2. Early warning flags -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "earlyWarningFlags" (
  "id" serial PRIMARY KEY,
  "fleetId" integer NOT NULL,
  "vehicleId" varchar(64) NOT NULL,
  "defectId" integer,
  "warningType" varchar(64) NOT NULL,
  "warningReason" text NOT NULL,
  "severity" varchar(32) NOT NULL DEFAULT 'medium',
  -- Stable key used to de-duplicate an active warning of the same kind for the
  -- same vehicle (e.g. "repeat_symptom:brakes"). Lets the rule engine refresh
  -- an existing active flag instead of inserting duplicates.
  "dedupeKey" varchar(255),
  "isActive" boolean NOT NULL DEFAULT true,
  "metadata" jsonb,
  "resolvedByUserId" integer,
  "resolvedAt" timestamp,
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "early_warning_fleet_active_idx"
  ON "earlyWarningFlags" ("fleetId", "isActive", "severity", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS "early_warning_vehicle_active_idx"
  ON "earlyWarningFlags" ("vehicleId", "isActive");
CREATE INDEX IF NOT EXISTS "early_warning_defect_idx"
  ON "earlyWarningFlags" ("defectId");
-- One active flag per (vehicle, dedupeKey): the rule engine upserts on refresh.
CREATE UNIQUE INDEX IF NOT EXISTS "early_warning_active_dedupe_idx"
  ON "earlyWarningFlags" ("fleetId", "vehicleId", "dedupeKey")
  WHERE "isActive" = true AND "dedupeKey" IS NOT NULL;

-- 3. Row-Level Security ------------------------------------------------------
-- Mirrors the project convention (0012 global enable, 0016 fleet-scoped reads):
-- writes go through the trusted backend (service_role); authenticated Supabase
-- clients may only read rows for fleets they belong to.
ALTER TABLE "earlyWarningFlags" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF to_regrole('service_role') IS NOT NULL THEN
    DROP POLICY IF EXISTS "service_role_full_access" ON "earlyWarningFlags";
    CREATE POLICY "service_role_full_access"
      ON "earlyWarningFlags"
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

DROP POLICY IF EXISTS "earlyWarningFlags_select_policy" ON "earlyWarningFlags";
CREATE POLICY "earlyWarningFlags_select_policy" ON "earlyWarningFlags"
  FOR SELECT USING (
    "user_has_fleet_access"("fleetId", "current_app_user_id"())
  );
